#https://blog.jinli.io/en/p/authentication-deploying-authelia-for-private-identity-service/

server:
  address: 'tcp://0.0.0.0:9091'

log:
  level: 'debug'

# STORAGE (Sessions, 2FA, Tokens) -> SQLite
storage:
  encryption_key: '8m&Kzp!X9$$Lz*Q^5v@B7+R1/N6=G4j9%W3_' # Must be 20+ chars
  local:
    path: '/config/db.sqlite3'

# User authentication: Simple file-based
authentication_backend:
  file:
    path: '/config/users_database.yml'
    watch: true 
    password:
      algorithm: argon2
      iterations: 3
      memory: 65536
      parallelism: 4

# https://www.authelia.com/overview/authorization/access-control/
access_control:
  default_policy: deny
  rules:
    - domain:
        - "*.lakehouse.local"
        - "lakehouse.local"
      policy: one_factor

session:
  secret: 'NBrEOEFUtsAcmQ9/bLdtuOHu4vL5DsM0x2FYaOz74l4zySeunrGDCtYE+2Ya2gSw'
  
  # How long you stay logged in
  expiration: '8h'
  inactivity: '2h'
  remember_me: '1M' # Allow 'Remember Me' for 1 month
  
  # Cookie Security
  same_site: 'lax'
  
  # Domain Config (The part you asked about)
  cookies:
    - name: 'authelia_session'
      domain: 'lakehouse.local'
      authelia_url: 'https://lakehouse.local:9091'
      default_redirection_url: 'https://lakehouse.local:8181' # Where to go after login

# OIDC PROVIDER
identity_providers:
  oidc:
    jwks:
      -
        key: |
          -----BEGIN PRIVATE KEY-----
          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxjZav2ouBuslw
          tGpJ5UVXsx+hk3Evs2blI9YDoyBfBKaAiKTtw522lotOI8aKAN3tB7wksmsLbVHa
          9TjQ/+HDVrMl2rs3K5nDv1xjR+NWAUN3gzfLfjme7zdJW+iDVxR7cUZuc+pNZ20l
          3ISVjFsvQ82NwTsfg2hLd9AIq4WMjz8O2DRRL9NF7RuLBgI+nmDvCqDKMP/ngu3K
          drkvq9qwfDBpfwbnmKmAj/b6rThDYdPRd55F7VVecfEusePtXQNBYX6B8RGYQiDy
          Nv+rHIylQ+OOlujJ3yVLpHeWvRwUkYI4dcp0/qbmFT9JrJetktJWInIr3o3HLrtS
          5IAB3nD3AgMBAAECggEAB75uX0WLGNPkzf48/xg5dl/Q+reXCq/qob1kdPW5x1sk
          fxJ/xCYfNVGK3JQaupqSE1VnYzs1LLV8HEC557n0vZPOG7+f/JQ6vfrwlIqBw7tO
          O8dAHadVor4nf6U7MfRrsMW+fwMwO/nfwU/pzLxCw0kvaGqQT1vDyzv74rzrPLea
          GC8N+ipmWXA9059ZW0t2vRqljYslRDdMCCCjuaJqxZg0b0gipwHoanscA9Pm+WWY
          TFcipSFxfeOMlunRjrnsYWqnG7K3i0ETeB/ajZnPo/vQdB/hZwU1JS1VZVAN7AS2
          wJcmHJzmXTNWrqmfdYAoREF/CEjHjej3CAwCzGUUVQKBgQDYHd1qA9MLm9Y5lr7q
          VXFyNkU8/ryA7Zi2D0epSvzt2zvGPu6m3IP5Kv9H79GRG0LD+g8loTWuEw0o5zmx
          CcTNDxXNrwo8psixMrwARN9LR5mHF7o7akjwjUrWDxT/DNKaTnVAHTM9xlKUDQE9
          x7EbnvdBuIoEawFz6iqAhFE98wKBgQDSUdcfr6lIn1wB0YZVGCdvKqwPzPQUyZCi
          MfJiX96RU0RxP884uB2P8shQnIMobOYR+j9LE83+oENDNM98Y8j2U9pSgLzlKBPD
          gkFREJKZWnBbM//sgRX6FZxmNslnLLQVQ0JqDtoLFNkDJfhU4LpVbvVPpogel3cT
          qrRONGJN7QKBgQCeqlZrRgGEzVWbFCx4OGDAvE1a+Z6FfWqXh2JSTSairkkVRBDM
          WqtdnI6tTslqIjyDSywhsViKw5vuwsvdSVG+Ruv4BSGb48sGJTxXajkRuLBjuSzW
          ADMqwGEIBSyiD9TyytVUS9vZ56eq4F1f8SL7J1taWdSiZ7k6U9n+XqaStwKBgG+f
          G8snUXLHkO8uIls7LIKlZRglsEzwBSDv3TI0q0z5olNwiCwUGyxwr7uItVtZIGne
          JIVWB3fh2pDqkEv2MYv6SN6MkLQWJxcWJFA/uW5GP2dIG8WLZPyLR6w/23g0k4bN
          YYwkQbir4dj35+o0MvBwqSUSvx9tR7daW8M9rgapAoGAcWZ8F+O7w8PVTH7+xXuM
          6gThuWpoyAGGaOuUmExVvztOAfGa9vFawNorgdjGdqUXyb2ihAptkzHwf/78bM3c
          JbMa2JgZVtes1sHgx2OlWfoZuUcMzIsOTpIUzX911ogB0qHynm5wsykJZKo2v/Xa
          IszdHHa1csErbga33YmGLx8=
          -----END PRIVATE KEY-----
    clients:
      - client_id: 'lakekeeper-client'
        client_name: 'Lakekeeper Catalog'
        client_secret: '$argon2id$v=19$m=65536,t=3,p=4$N6KdGQaCjL3z1nkyXxL5GQ$P0AGaR20Mp7fxSSrR7F8YzUhqMWuUwTs4VJGAtRXxo4'
        public: false
        authorization_policy: 'one_factor'
        redirect_uris:
          - 'https://lakehouse.local:8181/ui/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'

notifier:
  filesystem:
    filename: '/config/notification.txt'

identity_validation:
  reset_password:
    jwt_secret: '2y0+EZH/oLI+Jr1IvZW9CDZ9uxNS0H0harRWDT+77dN4pq0p'