#https://blog.jinli.io/en/p/authentication-deploying-authelia-for-private-identity-service/

log:
  level: 'debug'

server:
  address: 'tcp://0.0.0.0:9091/'
  tls:
    key: '{{ mustEnv "SERVER_TLS_KEY" }}'
    certificate: '{{ env "SERVER_TLS_CERT" }}' 

authentication_backend:
  file:
    path: /config/users.yml

identity_validation:
  reset_password:
    jwt_secret: '{{ mustEnv "AUTHELIA_JWT_SECRET" }}'

storage:
  encryption_key: '{{ mustEnv "AUTHELIA_STORAGE_ENCRYPTION_KEY" }}'
  local:
    path: /config/storage/db.sqlite3

session:
  secret: '{{ mustEnv "AUTHELIA_SESSION_SECRET" }}'

  cookies:
    - name: 'authelia_session'
      domain: '{{ mustEnv "DOMAIN" }}'
      authelia_url: 'https://auth.{{ env "DOMAIN" }}:9091'
      default_redirection_url: 'https://auth.{{ env "DOMAIN" }}:8181'

# https://www.authelia.com/overview/authorization/access-control/
access_control:
  default_policy: deny
  rules:
    - domain:
        - '*.{{ mustEnv "DOMAIN" }}'
        - '{{ mustEnv "DOMAIN" }}'
      policy: one_factor

notifier:
  filesystem:
    filename: /config/storage/notifications.txt