# users_database.yml
users:
  admin:
    displayname: "Data Admin"
    password: "$argon2id$v=19$m=65536,t=3,p=4$j7SEUhysO0QLaSsRTqWfsg$gWDiOtFxDcttnv23r/L53csfz/pDafU+IctyNMLzUOA"
    email: admin@example.com
    groups:
      - admins
      - data_engineers

  ds_user_1:
    displayname: "Daft User"
    password: "$argon2id$v=19$m=65536,t=3,p=4$x875EQ26BIFqITIiUwfwgA$sHX9/DqC8OzHJ15LvYZnnMo9fbJo47T4gkvypLqXE3E"
    email: ds_user_1@example.com
    groups:
      - data_scientists